name: Smurf Action
description: A custom GitHub Action that runs the Smurf CLI tool with Docker.

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  tool:
    description: 'Tool to use'
    required: true
  command:
    description: "Command to run (e.g., ./smurf stf init)"
    required: true

runs:
  using: "docker"
  image: 'ghcr.io/clouddrove/smurf:v1.0.0'
  args:
    - ${{ inputs.tool }}
    - ${{ inputs.command }}
