name: "Smurf"
description: "Build and push docker images"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tool }}
    - ${{ inputs.command }}

inputs:
  tool:
    required: true
  command:
    required: true
