name: Smurf Action
description: Automate Docker, Terraform, and Helm with Smurf GitHub Actions
branding:
  color: black
  icon: anchor

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  tool:
    description: 'Tool to use (e.g., stf)'
    required: true
  command:
    description: "Command to run (e.g., init)"
    required: true

runs:
  using: "docker"
  image: 'docker://ghcr.io/clouddrove/smurf:v1.0.0'
  args:
    - ${{ inputs.tool }}
    - ${{ inputs.command }}
