name: 'Setup Smurf CLI'
description: 'Install the Smurf CLI tool'
author: 'CloudDrove'

inputs:
  version:
    description: 'Version to install (e.g., 0.0.4-beta)'
    required: true
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install Smurf
      shell: bash
      run: |
        OS=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
        if [ "$OS" = "macos" ]; then
          OS="darwin"
        fi
        
        ARCH="amd64"
        if [ "$(uname -m)" = "arm64" ]; then
          ARCH="arm64"
        fi
        
        if [ "${{ inputs.version }}" = "latest" ]; then
          # Get latest version
          VERSION=$(curl -s https://api.github.com/repos/clouddrove/smurf/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
          URL="https://github.com/clouddrove/smurf/releases/latest/download/smurf-v${VERSION}-${OS}-${ARCH}.tar.gz"
        else
          VERSION="${{ inputs.version }}"
          URL="https://github.com/clouddrove/smurf/releases/download/v${VERSION}/smurf-v${VERSION}-${OS}-${ARCH}.tar.gz"
        fi
        
        echo "Downloading from: $URL"
        curl -sSL $URL | tar xz
        chmod +x smurf
        sudo mv smurf /usr/local/bin/
        echo "✅ smurf v${VERSION} installed!"