package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var (
	docsDir    string
	docsFormat string
)

// docsCmd generates the CLI reference from the live Cobra command tree, so
// the command reference can never drift from the code. It is hidden because
// it is developer/CI tooling, not something end users run.
var docsCmd = &cobra.Command{
	Use:    "docs",
	Short:  "Generate CLI reference documentation",
	Long:   `Generate CLI reference documentation for smurf from the current command tree, as markdown or man pages.`,
	Hidden: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := os.MkdirAll(docsDir, 0o755); err != nil {
			return fmt.Errorf("failed to create output directory %q: %w", docsDir, err)
		}

		// Suppress the "Auto generated by spf13/cobra on <date>" footer.
		// Without this, every generated file's timestamp changes daily even
		// when nothing else did, which would make the committed docs tree
		// and the CI drift guard falsely report a diff every day.
		RootCmd.DisableAutoGenTag = true

		switch docsFormat {
		case "markdown":
			if err := doc.GenMarkdownTree(RootCmd, docsDir); err != nil {
				return fmt.Errorf("failed to generate markdown docs: %w", err)
			}
		case "man":
			header := &doc.GenManHeader{
				Title:   "SMURF",
				Section: "1",
				Source:  "smurf",
			}
			if err := doc.GenManTree(RootCmd, header, docsDir); err != nil {
				return fmt.Errorf("failed to generate man pages: %w", err)
			}
		default:
			return fmt.Errorf("unsupported format %q, must be markdown or man", docsFormat)
		}

		return nil
	},
}

func init() {
	docsCmd.Flags().StringVar(&docsDir, "dir", "docs/sm/docs/cli", "directory to write generated documentation to")
	docsCmd.Flags().StringVar(&docsFormat, "format", "markdown", "output format: markdown or man")
	RootCmd.AddCommand(docsCmd)
}
