site_name: Smurf
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: https://clouddrove.com/assets/images/logo.png
  favicon: https://clouddrove.com/favicon.ico
  features:
    # - navigation.footer
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    # - content.code.annotations
    # - content.code.copy
    - navigation.sections
    - toc.integrate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


nav:
  - Home: index.md
  - Installation Guide:
      - Prerequisites: installation.md#prerequisites
      - CLI Installation: installation.md#cli-installation
      - GitHub Action Setup: installation.md#github-action-setup
  - Getting Started:
      - Running on Local CLI: getting-started.md#running-on-local-cli
      - Using in GitHub Actions: getting-started.md#using-in-github-actions
  - Usage:
      - CLI Commands: usage/cli-commands.md
      - GitHub Action: usage/github-action.md
      - Examples: usage/examples.md
  - Configuration:
      - Environment Variables: configuration.md#environment-variables
      - YAML/JSON Config Files: configuration.md#yamljson-config-files
      - Secrets Management: configuration.md#secrets-management
  - Integrations:
      - Docker: integrations/docker.md
      - Kubernetes: integrations/kubernetes.md
      - Helm: integrations/helm.md
      - Terraform: integrations/terraform.md
  - Advanced:
      - Troubleshooting: advanced/troubleshooting.md
      - Best Practices: advanced/best-practices.md
      - Contributing: advanced/contributing.md
  - FAQ: faq.md
  - Changelog: changelog.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

edit_uri: "https://github.com/clouddrove/smurf/tree/master/docs"

repo_url: https://github.com/clouddrove/smurf
repo_name: Smurf

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clouddrove
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clouddrove/

  generator: false 

extra_css:
  - css/custom.css

copyright: Copyright &copy; 2025 CloudDrove



