name: PR Checks Caller

on:
  pull_request:
    branches: ["master"]
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:

  claude-feedback:
    uses: clouddrove/github-shared-workflows/.github/workflows/claude-pr-review.yml@master
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
