name: PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@98bd1bc659ba3df111f725fc77488575f8dcf8ce