name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  handle-release:
    if: github.event.pull_request.merged == true
    uses: clouddrove/github-shared-workflows/.github/workflows/release-tag.yml@4b2ff708285026c1211445c4acb213af1c6ff3ba
    with:
      target_branch: ${{ github.event.pull_request.base.ref }}
      tag_format: "vX.Y.Z"  # or "X.Y.Z" depending on your preference
    secrets:
      GITHUB: ${{ secrets.GITHUB }}