name: Docker test build and push

on:
  push:
    branches:
      - feat/logs

env:
  GO_VERSION: 1.24
  REPO: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build the docker image
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: make image IMAGE=ghcr.io/${{ env.REPO }}:${{ github.ref_name }}

      - name: Tag latest
        run: docker tag ghcr.io/${{ env.REPO }}:${{ github.ref_name }} ghcr.io/${{ env.REPO }}:latest

      - name: Push
        run: docker push ghcr.io/${{ env.REPO }}:${{ github.ref_name }}

      - name: Push Latest
        run: docker push ghcr.io/${{ env.REPO }}:latest
